resolver: lts-10.4

packages:
- .
- location:
    git: https://github.com/parsonsmatt/esqueleto
    commit: e53f087d217c57994b01b648e11dab45ff1b797b
  extra-dep: true
  # - location:
  #     git: https://github.com/yesodweb/persistent
  #     commit: 4d0a6f3a4abde46c82691414e0e283a933a39f3e
  #   subdirs:
  #     - persistent
  #     - persistent-template
  #   extra-dep: true
  # - location:
  #     git: https://github.com/snoyberg/conduit
  #     commit: 7f75bfca8d479e1737861a75437a288af662a3cf
  #   extra-dep: true
  #   subdirs:
  #     - conduit
  #     - conduit-extra
  #     - resourcet

extra-deps:
  - conduit-1.3.0
  - resourcet-1.2.0
  - conduit-extra-1.3.0
  - persistent-2.8.1
